# Build performance
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Babric Beta 1.7.3
minecraft_version=b1.7.3
yarn_mappings=b1.7.3+build.8
loader_version=0.15.6-babric.2

# Vortex Client Babric port
mod_version=2.28.2-babric.1
maven_group=com.vortex
archives_base_name=vortexclient-babric-beta-1.7.3
