org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Legacy Fabric (https://legacyfabric.net/usage.html)
minecraft_version=1.8.9
yarn_build=604
loader_version=0.18.3
loom_version=1.16-SNAPSHOT
fabric_version=1.13.2+1.8.9

# Vortex Client fuer 1.8.9 -- eigene Versionsnummer, eigener Quelltext (Java 8)
mod_version=1.0.0
maven_group=com.vortex
archives_base_name=vortexclient-fabric-1.8.9
